name: 🚀 Release

on:
  workflow_dispatch:
    inputs:
      root_options:
        description: "Options: semantic-release <options>, es: --noop"
        default: "-v"
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    name: Release to PyPI 🐍
    permissions:
      id-token: write
      contents: write

    steps:
      - name: 📌 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🗂️ Generate Version and Changelog with Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          root_options: ${{ github.event.inputs.root_options }}

      - name: 🚧 Setup build environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: 🧩 Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: 📦 Build package distributions
        run: python -m build

      - name: 📤 Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
